#!/usr/bin/env bash
#
# Fails if the two tournament engines' conformance vectors have drifted apart.
#
# The web engine (tournament-game/src/lib/standings.ts) and the domain engine
# (tournament-game-api/app/Domain/Tournament/Standings/GroupTable.php) are two independent
# reimplementations of the same FIFA tiebreak ranking. They are pinned to each other by a
# shared set of vector files that BOTH must rank identically:
#
#   - standings.json       hand-authored golden cases (intended semantics, human-verified)
#   - standings.fuzz.json   generated by the web repo (`npm run vectors`); hundreds of
#                           reproducible random group shapes
#
# The web repo owns the canonical copy (test-vectors/); the api repo keeps a mirror
# (tests/Vectors/). Each engine's own test suite proves it ranks its local copy correctly.
# This script is the missing third guard: that the two copies never silently diverge.
# CI runs it on BOTH repos on every push (checking out the sibling), so a drift introduced
# on either side turns that repo's build red until the vectors are reconciled and committed
# together.
#
# Usage:  check-vectors-parity.sh <dir-a> <dir-b>
#   e.g.  scripts/check-vectors-parity.sh test-vectors ../tournament-game-api/tests/Vectors
#
set -euo pipefail

DIR_A="${1:?usage: check-vectors-parity.sh <dir-a> <dir-b>}"
DIR_B="${2:?usage: check-vectors-parity.sh <dir-a> <dir-b>}"

FILES=(standings.json standings.fuzz.json)
status=0

for f in "${FILES[@]}"; do
  a="$DIR_A/$f"
  b="$DIR_B/$f"

  if [[ ! -f "$a" ]]; then
    echo "MISSING  $a"
    status=1
    continue
  fi
  if [[ ! -f "$b" ]]; then
    echo "MISSING  $b"
    status=1
    continue
  fi

  if diff -q "$a" "$b" >/dev/null; then
    bytes=$(wc -c <"$a" | tr -d ' ')
    echo "OK       $f  (${bytes} bytes, identical)"
  else
    echo "DRIFT    $f  — the two engines' vectors differ:"
    diff -u "$a" "$b" | head -40 || true
    status=1
  fi
done

echo ""
if [[ $status -ne 0 ]]; then
  echo "Conformance vectors have DIVERGED between the two engines."
  echo "Reconcile: regenerate in the web repo (npm run vectors), copy BOTH files to the api"
  echo "repo's tests/Vectors/, and commit them together."
  exit 1
fi

echo "Both engines share byte-identical conformance vectors."
